### ISSUE TITLE
Example code or Docstring?

### ISSUE THREAD

**Issue by BrianPugh** [Manuscrit/SelectiveBackPropagation#1]
Could you provide a demo script using SelectiveBackPropagation and/or provide a docstring for the `__init__` method? Thanks!

**Comment by Manuscrit** [comment]
Done in https://github.com/Manuscrit/SelectiveBackPropagation/commit/3ebd4faae7a22d4016eaa1a27f45a01f7f381827 !

**Comment by BrianPugh** [comment]
thanks! It's much clearer now!
