### ISSUE TITLE
#Error 

### ISSUE THREAD

**Issue by LyesSaadSaoud** [Manuscrit/SelectiveBackPropagation#3]
Hello
When I run the code, I got the following error
self.loss_hist.extend(cpu_losses.tolist())
TypeError: 'float' object is not iterable

in the function :
def selective_back_propagation

Please help to correct it
Many thanks

**Comment by Manuscrit** [comment]
cpu_losses are the losses for each image in a batch (You must not use reduce in your loss)

**Comment by LyesSaadSaoud** [comment]
Thanks, I have used loos without reduce
criterion = nn.CrossEntropyLoss()
Please do have any tested implementation using your function
Many thanks

**Comment by LyesSaadSaoud** [comment]
I always get the same error even though I have used criterion = nn.CrossEntropyLoss(). 
Please any other suggestion
Thanks much

**Comment by Manuscrit** [comment]
In fact the reduce arg is depreciated. You must instead set the arg reduction to "none".

**Comment by LyesSaadSaoud** [comment]
Thanks, I have used loos without reduce
criterion = nn.CrossEntropyLoss()
I always get the same error even though I have used criterion = nn.CrossEntropyLoss().
Please any other suggestions.
Please do have any tested implementation using your function.
Many thanks

**Comment by LyesSaadSaoud** [comment]
Thanks much it works.
